### ISSUE TITLE
add ecology.bib to docs/sen2_mkl/docs

### ISSUE THREAD

**Issue by MKLau** [HFpostdoc/PitcherPlants#84]
Need it for rendering.

**Comment by amellison17** [comment]
Matt - can you clarify what you need here? My bibtex database? uploaded to github? Whatever it is, I'll do it early next week. Best from Maine, Aaron

**Comment by MKLau** [comment]
No worries, i just need the bib file/files for the citations in the sensitivity manuscript. They were here:

bibfiles "C:/Users/aellison.​FAS_DOMAIN/Dropbox/BigDataBook/BigDataLaTeX/bibtex/bib/misc/ecology"
options "C:/Users/aellison.​FAS_DOMAIN/Dropbox/LyX/bibtext/bst/amnat"

have fun in Maine!


Sent using CloudMagic Email<https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.4.10&pv=4.1.2&source=email_footer_2>
On Thu, Nov 05, 2015 at 4:34 PM, Aaron Ellison <notifications@github.com<mailto:notifications@github.com>> wrote:


Matt - can you clarify what you need here? My bibtex database? uploaded to github? Whatever it is, I'll do it early next week. Best from Maine, Aaron
